name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: runcycles/.github/.github/workflows/ci-java.yml@main
    with:
      pom-file: cycles-client-java-spring/pom.xml
      extra-steps: true
      extra-pom-install: cycles-client-java-spring/pom.xml
      extra-pom-compile: cycles-demo-client-java-spring/pom.xml
